### ISSUE TITLE
Bug in Composer2 cmd Windows 10 [RuntimeException]

### ISSUE THREAD

**Issue by Avalon18** [nikosdion/joomlatypehints#5]
Bug in cmd Windows 10 pro 20H2
 [RuntimeException]                                                            
  require.nikic/PHP-Parser is invalid, it should not contain uppercase characters. Please use nikic/php-parser instead.
// in composer.json "require":
//  "nikic/PHP-Parser": "^4.0@dev",
"nikic/php-parser": "^4.0@dev",
 if lowercase letters 'composer install' is Ok
![2021-01-06_08-48-48](https://user-images.githubusercontent.com/3528353/103734073-31c0bd80-4ffc-11eb-8c6a-1b17d51eae21.png)

**Comment by nikosdion** [comment]
This is not Windows 10 specific, it's because you are using Composer 2. It just needs a small change in composer.json. I'll make the change and will update this issue here.

**Comment by nikosdion** [comment]
I have fixed the composer.json. You can `git pull` and retry now.

**Comment by Avalon18** [comment]
Thank you everything works!
I use in Win10 - .bat script 'cmd-joomlatypehints-install.bat' for auto generate, maybe it may be useful for you

`@ECHO off
SETLOCAL EnableExtensions EnableDelayedExpansion
CHCP 65001
ECHO -----------------
ECHO Delete old folder \joomlatypehints:
RD /q /s %~dp0\joomlatypehints
ECHO OK
ECHO -----------------
ECHO install joomlatypehints:
ECHO git clone https://github.com/nikosdion/joomlatypehints.git
CALL git clone https://github.com/nikosdion/joomlatypehints.git
CALL cd joomlatypehints
CALL composer install
ECHO OK
ECHO -----------------
ECHO Generating documentation for Joomla!
SET /p "ch=Set version:"
ECHO Generating documentation for a version: %ch%
ECHO php typehints.php generate --for-version=%ch%
ECHO -----------------
CALL php typehints.php generate --for-version=%ch%
ECHO OK
ECHO -----------------
PAUSE`
